### ISSUE TITLE
how do we want to template deletion or set via `config` command?

### ISSUE THREAD

**Issue by yeled** [yeled/napalm-opengear#15]
Leaving XML aside for now, probably a v2 feature..

How do we want to expect the NAPALM template to configure the action of "delete" vs "set"?

@fjaeckel and I spoke about this on Slack and thought that matching the `config` setting of "if a var is missing, it's a delete.

`config -d var.foo`

If the var is set (we can match a literal `=` character) then it's a `config -s var.foo=quux`.

```jinja2
var.foo=1
{% some stuff %}
quux.bar={{ some["stuff"] | default("Hello") }}
baz
{% some other stuff %}
```

Would come to:

```
config -s var.foo=1
config -s quux.bar=Hello
config -d baz
```
What do you think @r0bertw ?

The only problem I see is that it's hard to immediately spot, if you had hundreds of lines of var=foo, and one was missing a `=` it might take a lot to find out why some config was being deleted.

We _could_ explicitly just pass the `-d` and the `-s` from the template, but then a `config -g config` wouldn't be restorable, you'd need to insert a `-s` before each line.

**Comment by fjaeckel** [comment]
> The only problem I see is that it's hard to immediately spot, if you had hundreds of lines of var=foo, and one was missing a = it might take a lot to find out why some config was being deleted.

We could have a test checking for the validity of the configuration, no?
Does opengear allow bogus configuration variables being set? When a `=` is missing it would be a bogus variable.

**Comment by r0bertw** [comment]
The config get/set/delete commands are really just a direct interface into the XML file and while it doesn't do any validation of the data, it checks basic command syntax and will print an error and return 1 if you run say: `config -s config.foo`

**Comment by yeled** [comment]
The reason we use the `config` statements is that it's easy to parse, and easy to diff.

Diffing XML is a bit of a pain, so I went with this more basic 2-dimensional setup as a good first step.

Sounds like I will go ahead with my idea and rely on config error catching.

If anyone has ideas for how to jinja-ilize XML I am all ears. We should spike an issue for that.
