### ISSUE TITLE
get_users() support?

### ISSUE THREAD

**Issue by yeled** [yeled/napalm-opengear#16]
How should we best support get_users() and support changing password hashes?

Is it all in /etc/config/shadow? are they hashed in a secure way?

Finding the groups would also be beneficial. I know how to set and remove groups with `user-mod` and tbh I prefer to delete the user and start afresh as I've seen group changes not "stick" (just anecdotally) when trying to remove them with that tool.

If we remove and delete users every time people might be surprised their ~ disappears.

**Comment by r0bertw** [comment]
All passwords are MD5 hashed in /etc/shadow and not stored in config.xml, *except* for users that are in the PSTN _dialin_ group (we recommend using a separate auxiliary account for dialin auth).

You can set the **config.users.userX.password** field to whatever you want writing directly to the shadow file's encrypted password field, or you can set **config.users.userX.plaintext_password** and the configurator will encrypt it for you.  In both cases the passwords are removed from config.xml by the configurator as it runs.

The examples at the end of KB article might be useful: https://opengear.zendesk.com/hc/en-us/articles/216371303-Managing-local-users-from-the-command-line

If you remove and then re-add a user and then finally run the configurator, I would've thought the user's homedir would be untouched.

**Comment by yeled** [comment]
> you can set **config.users.userX.plaintext_password** and the configurator will encrypt it for you. In both cases the passwords are removed from config.xml by the configurator as it runs

Wow really! I had to strip `plaintext_password` from the XML for our own security reasons. Let me experiment with that.

It sounds delightful being able to run `config -s config.users.${foo}.password=${bar}` with the same MD5 hash that's in `/etc/shadow`! This would be Junos and EOS parity.

**Comment by yeled** [comment]
Just had a call with OpenGear. Perhaps we should limit opengear support to >4.6.0 and use the API instead?

**Comment by yeled** [comment]
> and use the API instead?

oh, https://ftp.opengear.com/download/api/cs/og-cs-rest-api-specification-v1.4.html#users_get doesn't fetch the password.

We'll need to scrape `/etc/shadow` if we wanted parity with say, [junos](https://github.com/napalm-automation/napalm/blob/develop/napalm/junos/junos.py#L2101).

Or we just never report the password? might be much easier and on message with the OpenGear way.

**Comment by r0bertw** [comment]
The API on our mainstream “OG” products (IM, ACM, CM) doesn’t have full parity with UI/CLI, so I’d probably continue via CLI.
